version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=podcast_user
      - DB_PASSWORD=podcast_password
      - DB_NAME=podcast_platform
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=podcast_platform
      - MYSQL_USER=podcast_user
      - MYSQL_PASSWORD=podcast_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
